### ISSUE TITLE
pip install missing setup_cython.py

### ISSUE THREAD

**Issue by proximous** [fabioz/PyDev.Debugger#102]
I want to do remote debugging on an arm from PyCharm on x86, so I `pip install pydevd` on the arm.  

When I start my program I see 
`warning: Debugger speedups using cython not found. Run 'python "/usr/local/lib/python3.5/dist-packages/setup_cython.py" build_ext --inplace' to build`
however setup_cython.py is not installed with pip.

Is this expected?  How should I build the speedups on the arm?  Thanks.

**Comment by fabioz** [comment]
Seems like an issue in packaging... you can copy the setup_cython.py from the project to your local install for now as a workaround (https://github.com/fabioz/PyDev.Debugger/blob/master/setup_cython.py).

**Comment by james-johnston-thumbtack** [comment]
This is also affecting me.  Not doing anything cross-platform with ARM, just installing it via the normal "pip install pydevd" and getting the above warning.  But setup_cython is missing.

In my case, I'm setting up pydevd inside of a Docker image; it's installed as part of a larger pip requirements.txt file.  I'd rather not be having to use wget setup_cython.py and would prefer to have this installed as part of the pip package.

**Comment by fabioz** [comment]
Added to distribution (next release will have it).
