### ISSUE TITLE
virtualenv debug fails 

### ISSUE THREAD

**Issue by gaborbernat** [fabioz/PyDev.Debugger#103]
generates args for pip:

``['install', '--ignore-installed', '--cert', 'C:\\Users\\berna\\AppData\\Local\\Temp\\tmplw7i_yd7', 'C:\\Program Files\\JetBrains\\PyCharm 2017.3\\helpers\\pydev\\pydevd.py', '--port', '3208', '--client', '127.0.0.1', '--multiproc', '--file', 'setuptools', 'pip', 'wheel']``

**Comment by fabioz** [comment]
Please be more detailed in your report on what you're trying to accomplish and how to reproduce the error.

**Comment by gaborbernat** [comment]
1. clone https://github.com/pypa/virtualenv with any PyCharm
2. run the tests with attach to subprocesses on, test_always_copy_option
3. https://github.com/fabioz/PyDev.Debugger/blob/master/_pydev_bundle/pydev_monkey.py#L97 patches the input wrongfully and running the script https://github.com/pypa/virtualenv/blob/master/virtualenv.py#L855 fails as the cli args for pip will be:  ``'install', '--ignore-installed', '--cert', 'C:\\Users\\berna\\AppData\\Local\\Temp\\tmplw7i_yd7', 'C:\\Program Files\\JetBrains\\PyCharm 2017.3\\helpers\\pydev\\pydevd.py', '--port', '3208', '--client', '127.0.0.1', '--multiproc', '--file', 'setuptools', 'pip', 'wheel'```

**Comment by gaborbernat** [comment]
note this is https://youtrack.jetbrains.com/issue/PY-27594, pydev does not support stdin for subprocess

**Comment by gaborbernat** [comment]
Note this is now fixed via https://github.com/JetBrains/intellij-community/pull/790, and present in upstream.
