### ISSUE TITLE
Missing Python support trove classifiers in setup.py

### ISSUE THREAD

**Issue by cclauss** [fabioz/PyDev.Debugger#111]
https://python3wos.appspot.com
https://pypi.org/pypi?%3Aaction=list_classifiers
https://github.com/fabioz/PyDev.Debugger/blob/master/setup.py#L133-L147

**Comment by cclauss** [comment]
Does the current release on PyPI support Python 3?  https://python3wos.appspot.com still says _not_.

**Comment by fabioz** [comment]
It does... I still haven't released a version with the updated classifiers
(but the repo is already correct, just waiting for me to have time to do a
release).

**Comment by hugovk** [comment]
I see the version classifiers added in https://github.com/fabioz/PyDev.Debugger/pull/112 were removed in the 1.2.0 release:

https://github.com/fabioz/PyDev.Debugger/commit/f5fec252c008074652ece29c8b68c159083673ae#diff-2eeaed663bd0d25b7e608891384b7298

And they're missing from PyPI:
* https://pypi.org/project/pydevd/
* https://pypi.org/pypi/pydevd/json

Was there a special reason for removing them? It would be good to have PyPI reporting the supported versions. Thanks!
