### ISSUE TITLE
Using PyDev in Pycharm with Python 2.3 interpterer

### ISSUE THREAD

**Issue by tonysepia** [fabioz/PyDev.Debugger#114]
I have some old libraries for SAP's MAX DB that were compiled for 32-bit OS and a custom 2.3 python interpreter.

I can run the code from PyCharm, but can't debug it, as some of PyDev's syntax (the use of Finally and Except as e) is not compatible with 2.3

Of course I can't expect you to support such an old interpreter, but could you please suggest what can be done? 

Thank you!

**Comment by fabioz** [comment]
You should get an older version of the debugger too (which should be available in an older version of PyDev or PyCharm).

**Comment by tonysepia** [comment]
Thank you for your repsponse! Could you please point me to an older version of PyDev debugger that is compatible with Python 2.3? Does that version exist?

**Comment by fabioz** [comment]
Well, the PyDev debugger without a compatible client is not very useful...

The version I believe will work on Python 2.3 is PyDev 2.8.2 (You need Eclipse 3.8 and use the update site: http://www.pydev.org/update_sites/old/).

Related to PyCharm, I have no idea which version would be compatible.

**Comment by tonysepia** [comment]
Thank you!

**Comment by murali-darvaja** [comment]
@tonysepia have you found the solution for this?. If you found it can you please post it here, that would be very helpful for me. I'm using Jython2.5, so I'm also facing same problem.

**Comment by tonysepia** [comment]
Not yet, @murali-darvaja, but I will post here if I ever have to get back to this old library that I was trying to use.

**Comment by murali-darvaja** [comment]
@tonysepia for Jython2.5, I'm using Pycharm2016.3.3 (Professional). Debugging is working fine without any exceptions on this version.
