### ISSUE TITLE
AssertionError for WIN platform in set_ide_os method in pydevd_file_utils files

### ISSUE THREAD

**Issue by nedo99** [fabioz/PyDev.Debugger#117]
Hello,

I tried remote debugging with `pydevd `but it fails due to `AssertionError `in `set_ide_os `method. I start debug server on local machine, Windows 10, and try to connect to that debug server from remote host. I get following error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/_pydevd_bundle/pydevd_process_net_command.py", line 74, in process_net_command
    pydevd_file_utils.set_ide_os(ide_os)
  File "/usr/local/lib/python3.5/dist-packages/pydevd_file_utils.py", line 172, in set_ide_os
    assert os in ('WINDOWS', 'UNIX')
AssertionError
```

The reason why it fails is because an `os `variable is `WIN`. Is this way it was supposed to behave or it is an issue? If I modify the script to include `WIN ` string as well, then it connects to a debugger.

Looking forward to your reply!

Regards,
Nedim

**Comment by fabioz** [comment]
I've already fixed in the repo to account for this (it seems PyCharm used this form instead of `WINDOWS` as PyDev used) -- until that's released you can fix locally as you did.
