### ISSUE TITLE
Unable to do dynamic path mapping with remote debuggin

### ISSUE THREAD

**Issue by nedo99** [fabioz/PyDev.Debugger#118]
Hello,

I am using a PyCharm for remote debugging and would like to have dynamic path mapping since remote python script (running on Linux) is not fixed location. Looking at the `pydevd_file_utils.py` source I tried to export `PATHS_FROM_ECLIPSE_TO_PYTHON ` variable or even to set it in `pydevd_file_utils.py ` source code manually on the remote Linux machine just to test it:
```
PATHS_FROM_ECLIPSE_TO_PYTHON = [
  (r'C:\\Users\\my_username\\workspace',
   r'/home/my_username/src_folder')
 ]
```

but there is no effect. Debug server is started with PyCharm on Win 10 machine and remote script starts on the Linux machine. I also tried this approach[ https://stackoverflow.com/questions/7999526/is-there-any-way-to-modify-the-pydevd-file-utils-paths-from-eclipse-to-python-va]( https://stackoverflow.com/questions/7999526/is-there-any-way-to-modify-the-pydevd-file-utils-paths-from-eclipse-to-python-va), but without luck.

Is this possible at all with PyCharm? Or this should be exported on the host where debug server is running?

Looking forward to your reply.

Regards,
Nedim

**Comment by nedo99** [comment]
Any updates on this one? 

Regards,
Nedim

**Comment by fabioz** [comment]
Hi Nedim,

Not sure why it's not working there... in theory if you have an env variable names `PATHS_FROM_ECLIPSE_TO_PYTHON` with the proper json contents (in the server where you're running python), it should work (just tested and it does work for me).

I don't think PyCharm has anything special regarding it vs PyDev (which is where I tested). Anyways, as it's working for me, I'm closing this issue (you can try to ask the PyCharm guys on their tracker to see if they have anything special there).
