### ISSUE TITLE
pydev debugger: warning: trying to add breakpoint to file that does not exist

### ISSUE THREAD

**Issue by gigi206** [fabioz/PyDev.Debugger#125]
Hello,

I use VSCode with extension ms-python.python-2018.9.1 and I use python under [msys2](https://www.msys2.org/) ([cygwin](https://cygwin.com) like) :
```
$ python
Python 3.6.6 (default, Jun 28 2018, 10:27:26)
[GCC 7.3.0] on msys
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.platform
'msys'
>>>
```

When I try to debug a python file I have the following message :
```
pydev debugger: warning: trying to add breakpoint to file that does not exist: /:\Users\gigi\Desktop\python\gigix.py (will have no effect)
```

From pydevd_file_utils.py file, if I replace L231 by the following line, it works :
```
        real_path = subprocess.getoutput("cygpath -a '{}'".format(filename))
```
https://github.com/fabioz/PyDev.Debugger/blob/839bd5e891f15d30d6188617a45ac9a319c38221/pydevd_file_utils.py#L231

Is it possible to add a test to determine the path under cygwin / msys2 ?

**Comment by fabioz** [comment]
As you're using this under vscode, please report this to https://github.com/Microsoft/ptvsd.
