### ISSUE TITLE
Re-enable frame eval: set next statement

### ISSUE THREAD

**Issue by Elizaveta239** [fabioz/PyDev.Debugger#131]
Hi! It looks like the latest changes in frame evaluation debugger broke "Set next statement" action: debugger started to execute the line under the cursor (target of the jump) in frame eval mode. It works fine without frame evaluation.
I wanted to fix it myself, but there are some major changes, which I don't want to fix without your advice. 

In the original frame eval debugger we inserted the following code:
```
def pydev_trace_code_wrapper():
    global _pydev_stop_at_break
    return _pydev_stop_at_break()
```
So it returned a value, which we used as a flag for jump instruction and which helped us to avoid code execution while jumping (that's why we're inserting jump instruction [here](https://github.com/fabioz/PyDev.Debugger/blob/master/_pydevd_frame_eval/pydevd_modify_bytecode.py#L177))
But now this function doesn't return any value and I have no idea how it can be fixed.
How do you think, should we revert `return` to inserted code? Or maybe you have some ideas how to fix the issue without returning value from the function? 
Thank you!

**Comment by fabioz** [comment]
Set next statement should be working on master -- just checked here.

The approach for frame eval changed to do the following: run untraced until the stop at break is called... when the stop at break is called, all it does is set the tracing to be on and when tracing starts the breakpoint will trigger in regular trace mode (in which case the set next statement should work properly).

Note that there's even an automated test for this: https://github.com/fabioz/PyDev.Debugger/blob/master/tests_python/test_debugger.py#L1320, so, closing this issue.

**Comment by Elizaveta239** [comment]
Yes, I've seen the test, but you check value not right after jump, but after Step Over. If I add expression evaluation right after jump, value `a = 1` already (so line 2 was executed). Could you please check it again?

**Comment by fabioz** [comment]
Ok, I was able to reproduce it now (test is failing). Will take a look at it tomorrow.
