### ISSUE TITLE
Breakpoints on code inside qt won't hit in some cases, if matplotlib is imported

### ISSUE THREAD

**Issue by tarcisiofischer** [fabioz/PyDev.Debugger#137]
This seems a very specific situation, and I couldn't yet make a small test case that embraces the full workflow. I'll expose the problem here and propose some solutions, but feel free to further discuss.

Given that this code exists: https://github.com/fabioz/PyDev.Debugger/blob/master/pydev_ipython/inputhookqt5.py which, as I see, is a bugfix for a very specific case. And assuming that it is called here: https://github.com/fabioz/PyDev.Debugger/blob/4fc8f1679fda5cf61c430c5f465583a9f7c8c565/pydevd.py#L1160-L1163 , which happens when a breakpoint is being executed, for example.

And because the hook calls `qt.process_events`, and I'm on a qt application that imports matplotlib AND have qt5 gui implementations, then, if I add a breakpoint in a callback that happens to be executed in this process_events call inside this hook, the breakpoint won't hit (In my case, I had a breakpoint in a `print("hi")` code inside a qt callback on python, and I saw the print on output, but my breakpoint never hits).

**Possible solutions**

1) Do NOT process all qt events here: https://github.com/fabioz/PyDev.Debugger/blob/master/pydev_ipython/inputhookqt5.py#L112, but, instead, only the keyboard event. I don't know if this is possible;

2) Give me the opportunity to DO NOT register this hook. Is there any way I can disable it, without having to change the source code?

3) Support breakpoints inside this workflow-case; But I have no idea how this could be done.

Please let me know if this is enough to understand the problem. If not, I can work further on isolating the problem in a small test case (Would probably take some time, though).

Thanks in advance.

**Comment by tarcisiofischer** [comment]
For now, a fix that seems to be working for me is to make the following change in `pydevd.py` (I'm using LiClipse 5.0.2, and this file is on path `LiClipse 5.0.2\plugins\org.python.pydev.core_6.4.4.201807281547\pysrc\pydevd.py`)

Change this code:
```
        while info.pydev_state == STATE_SUSPEND and not self._finish_debugging_session:
            if self.mpl_in_use:
                # call input hooks if only matplotlib is in use
                self._call_mpl_hook()

            self.process_internal_commands()
            time.sleep(0.01)
```

to this:
```
        while info.pydev_state == STATE_SUSPEND and not self._finish_debugging_session:
            self.process_internal_commands()
            time.sleep(0.01)
```

**Comment by fabioz** [comment]
@tarcisiofischer well, that's added so that when you're at a given breakpoint you can interact with the application and see plots (but as you noted, you can't hit new breakpoints when already inside a breakpoint), so, the solution in your case would be leaving that breakpoint (i.e.: resuming execution) to go to the actual app event loop and then executing the action (which should hit breakpoints then).

Now, I agree this may be confusing, so, a setting to enable or disable that integration is probably reasonable (there's already such a setting for the interactive console and there should be one for the debugger too).

**Comment by tarcisiofischer** [comment]
I'm searching where this "setting for interactive console" is done, but I don't know exactly where/how to search.

What I did was to use github's search engine to check where `create_inputhook_qt5` is used and then further dig from this place, hoping to find something. I got no luck doing that. Do you know where this is done, so I can see the actual code?

What I'm trying to do is to understand how this settings mechanism work, so that I can mimic it for the debugger.

**Comment by fabioz** [comment]
As I think this is a corner case, lets make it easier: just check for an environment variable (say PYDEVD_PROCESS_UI_LOOP_ON_BREAKPOINT=0|1, where the default when not there is 1).

What do you think?
