### ISSUE TITLE
configurable debugger connect timeout

### ISSUE THREAD

**Issue by thehesiod** [fabioz/PyDev.Debugger#138]
We have a custom deploy where we manually call `pydevd.settrace`, however it's not reasonable that the user only has 10s or so to start the debugger, especially if you're debugging multiple services at the same time.  I propose having the timeout configurable as a parameter.  From what I saw right now there's no way besides monkey patching the connect method: https://github.com/fabioz/PyDev.Debugger/blob/master/_pydevd_bundle/pydevd_comm.py#L418

**Comment by thehesiod** [comment]
like this: https://github.com/fabioz/PyDev.Debugger/pull/139?

**Comment by fabioz** [comment]
> like this: #139?

Yeap ;)
