### ISSUE TITLE
Failing import of module _pydevd_bundle._debug_adapter in pydevd 1.5.0

### ISSUE THREAD

**Issue by mforkel** [fabioz/PyDev.Debugger#140]
After upgrading to pydevd 1.5.0 from 1.4.0, I get an ImportError for a non-existing module _pydevd_bundle._debug_adapter, which _pydevd_bundle.pydevd_process_net_command_json tries to import. My debug server is the one bundled with PyDev 7.1.0.

**Comment by fabioz** [comment]
I'll take a look at it (seems like a packaging issue).

**Comment by mforkel** [comment]
I tried two ways: My old packaging for Debian Stretch (worked for pydevd 1.4.0) and 'pip install pydevd' in a clean virtual environment.

**Comment by fabioz** [comment]
The version distributed in `pip` really had an issue (although the version bundled on PyDev itself seems to be Ok).

Just did a new release (1.5.1) where the packaging issue should be fixed.

**Comment by mforkel** [comment]
Version 1.5.1 works fine here.
