### ISSUE TITLE
Python 3 syntax errors in pydevd source

### ISSUE THREAD

**Issue by mforkel** [fabioz/PyDev.Debugger#141]
I'm trying to package pydevd for Debian in order to support remote debugging. Installation of the Python 3 version of the package fails because a couple of syntax errors are found during the automatic byte compilation:
```
File "/usr/lib/python3/dist-packages/_pydev_imps/_pydev_SimpleXMLRPCServer.py", line 263
    except Fault, fault:
                ^
SyntaxError: invalid syntax

  File "/usr/lib/python3/dist-packages/_pydev_imps/_pydev_SocketServer.py", line 339
    print '-'*40
            ^
SyntaxError: Missing parentheses in call to 'print'

  File "/usr/lib/python3/dist-packages/_pydev_imps/_pydev_inspect.py", line 293
    raise TypeError, 'arg is a built-in module'
                   ^
SyntaxError: invalid syntax

  File "/usr/lib/python3/dist-packages/_pydev_imps/_pydev_pkgutil_old.py", line 543
    except IOError, msg:
                  ^
SyntaxError: invalid syntax

  File "/usr/lib/python3/dist-packages/_pydev_imps/_pydev_uuid_old.py", line 151
    if not 0 <= time_low < 1<<32L:
                                ^
SyntaxError: invalid syntax

  File "/usr/lib/python3/dist-packages/_pydev_imps/_pydev_xmlrpclib.py", line 294
    True, False = True, False
    ^
SyntaxError: can't assign to keyword

  File "/usr/lib/python3/dist-packages/_pydevd_bundle/pydevconsole_code_for_ironpython.py", line 105
    except SyntaxError, err:
                      ^
SyntaxError: invalid syntax

  File "/usr/lib/python3/dist-packages/_pydevd_bundle/pydevd_exec.py", line 3
    exec exp in global_vars, local_vars
           ^
SyntaxError: Missing parentheses in call to 'exec'

  File "/usr/lib/python3/dist-packages/pydev_ipython/inputhookglut.py", line 98
    print '\nKeyboardInterrupt'
                              ^
SyntaxError: Missing parentheses in call to 'print'
```

Since installing pydevd with pip and using `pydevd.setrace` in a virtual environment with Python 3 works fine, I guess the above files (and probably some more) are simply not used. Is there a way to identify which modules I have to include in the package and which I can exclude?

**Comment by fabioz** [comment]
Well, those files are needed to support older versions of python or ironpython and really aren't used in Python 3 (they aren't really valid on py3 as you noted). Unfortunately, there's not a really good way to identify it (although those that have syntax errors are definitely not valid).

**Comment by fabioz** [comment]
Closing as I think there's not much to be done on the `pydevd` side as those files aren't used unless you're on Python 2 (and as you noted `pip install` works on py2 and py3).

Feel free to add more comments if you want additional info or if you think something needs to change on `pydevd`.

**Comment by mforkel** [comment]
Trying to keep things simple (for me), I decided to suppress automatic byte-compilation for the Python 3 package. Calling `pydevd.settrace` in a Python 3 script for the first time resulted in 76 of 129 pydevd modules being byte-compiled (by the count of .pyc and .py files). It might be more with different options to `pydevd.settrace`. So if there was as manifest  file stating which modules are needed for Pyhon 2 and Python 3 respectively on Linux, the Debian packages could be trimmed down quite a bit.

Do you think the creation of reliable manifest(s) could be automated with a script that calls `pydevd.settrace` with varying options and then identifies the byte-compiled pydevd files in a virtual environment?

**Comment by fabioz** [comment]
> Do you think the creation of reliable manifest(s) could be automated with a script that calls `pydevd.settrace` with varying options and then identifies the byte-compiled pydevd files in a virtual environment?

I think this can be tricky as `pydevd` makes no guarantees about it... I think the safest path would be compiling everything possible while ignoring syntax errors.
