### ISSUE TITLE
NameError: jinja2

### ISSUE THREAD

**Issue by p74** [fabioz/PyDev.Debugger#145]
I got a error in eclipse and i really don't know the cause of this error but it seems to be related to pydev
I use eclipse version 
Version: 2019-03 (4.11.0)
Build id: 20190314-1200

/.local/lib/python3.6/site-packages/_pydevd_bundle/pydevd_process_net_command.py", line 685, in process_net_command
    raise NameError(exception_type)
NameError: jinja2

**Comment by jkoan** [comment]
Got the same issue with PyDev 8.0.0. For me it was a outdated pydevd lib on the serverside.

**Comment by fabioz** [comment]
Thanks for the report... I've never been able to reproduce this, so, I guess that having an outdated version does make sense on how it could happen.
