### ISSUE TITLE
Pydevd prints unexpected messages when beginning a trace

### ISSUE THREAD

**Issue by coredumperror** [fabioz/PyDev.Debugger#158]
Ever since a month or two ago, Ive been seeing these two lines print to my docker console every time I start a new pydevd trace: 

```
Expected: %s to exist.
NoneType: None
```

It took me a while to track down where these were coming from; I just traced them to pydevd today. I run Pydevd in a Django middleware using the following command:
```
    pydevd.settrace(host=host, port=port, suspend=False, trace_only_current_thread=True)
    response = get_response(request)
    pydevd.stoptrace()
```

`host` and `port` are populated with the same values i've been using for many months, and I've been using `suspend=False, trace_only_current_thread=True` for quite a long time, too. So I'm not really sure why this suddenly started happening some time around mid November (if I recall correctly). Maybe there's a new bug in pydevd that no one else has noticed/reported?

I regularly update pydevd to the latest version, because PyCharm complains at me when I update it and don't also update the pydevd-pycharm package. I currently use pydevd-pycharm version 193.5662.61, alongside PyCharm version 2019.3.1.

I looked through the code and I *think* I've found the source of the first error message. Line 144 in `pydevd_tracing.py`:

```
        pydev_log.critical('Expected: %s to exist.', filename)
```

It's strange that the `filename` is not being interpolated into the error message string, but maybe that's a clue as to why this is printing at all? 

From reading the code, I realize that `filename` seems to change depending on your OS, so I should say that I'm running macOS Mojave, though my code is actually running in a CentOS 7 container running within the latest version of Docker Desktop (v2.1.0.5). Python is v3.6.8, Django is v2.0.5.

Nothing's "broken", but these spurious printouts on every single web request are pretty annoying.

**Comment by fabioz** [comment]
Hi @coredumperror PyCharm doesn't use the same version as pydevd (it's a fork which has their own changes). As such, please report this error to them as I don't think this is an error in `pydevd` (the version in `pydevd` does interpolate that properly).
