### ISSUE TITLE
inject_dll_x86.exe being flagged as a trojan by Microsoft Defender

### ISSUE THREAD

**Issue by RJacksonm1** [fabioz/PyDev.Debugger#159]
Heyo,

The IT folk at my office got an alert about a trojan sneaking up on my machine. It's shouting about `~/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd_attach_to_process/inject_dll_x86.exe`.

[VirusTotal doesn't seem too worried about it](https://www.virustotal.com/gui/file/f81d548d496f96c621b45e2be83683f79becd8653afbcea9d411f311adddeea2/detection), and this is Microsoft Defender complaining about binaries that have been shipped with Microsoft's official Python language extension for Visual Studio Code... Almost certainly feels like a false positive.

Regardless, thought it best to flag y'all in case there is something dodge going on!

**Comment by fabioz** [comment]
This has been raised in https://github.com/microsoft/ptvsd/issues/2028 (so, I'm closing this here).

**Comment by TechRemedies** [comment]
@fabioz The inject_dll_x86.exe file has been quarantined by some anti-virus. It is being marked as suspicious in [VirusTotal ](https://www.virustotal.com/gui/file/151ba420e5b2e8d49d035a38a1ad07e1e8114801a02dba4cd0ff8695ebc4e6b2) again. 

This version has the SHA256 Hash of: 151ba420e5b2e8d49d035a38a1ad07e1e8114801a02dba4cd0ff8695ebc4e6b2
