### ISSUE TITLE
Debugger doesn't stop on  exception breakpoint

### ISSUE THREAD

**Issue by trofimander** [fabioz/PyDev.Debugger#16]
Python 2.5 and 2.7

Run the following code:

```
def foo(x):
    return 1/x

def zoo(x):
    res = foo(x)
    return res

print(zoo(0))

```

With exception breakpoint: exceptions.ZeroDivisionError

=> Debugger doesn't stop

**Comment by Atcold** [comment]
@fabioz, where is the setting "break on rise" you're mentioning?
I think this is what is going on right now on my system...

**Comment by fabioz** [comment]
@Atcold In PyDev, go to the debug perspective > PyDev > Manage exception breakpoints.

**Comment by Atcold** [comment]
Yeah, I found it at Run > View Breakpoints.
Any idea how that option toggled itself?
