### ISSUE TITLE
Missed Placeholder without a value

### ISSUE THREAD

**Issue by rafaelcapucho** [fabioz/PyDev.Debugger#163]
Hi,
I'm getting this error:
![image](https://user-images.githubusercontent.com/163367/74121707-6be4cd80-4ba7-11ea-998f-613fde41a5cc.png)

but I think that it shouldn't be showing the placeholder `%s`, it is missing the param to fill the str:
https://github.com/fabioz/PyDev.Debugger/blob/6eccf884621c0314461c596a62e2b1be62690711/pydevd_tracing.py#L144

**Comment by fabioz** [comment]
This isn't a problem in `pydevd` but rather in the fork that `PyCharm` is using (they probably haven't updated the logging module to support that construct but did update that module)... 

So, please report to them instead.
