### ISSUE TITLE
Breakpoint won't catch from daemon thread

### ISSUE THREAD

**Issue by ryanmkurtz** [fabioz/PyDev.Debugger#171]
[Ghidra](https://github.com/NationalSecurityAgency/ghidra) uses Jython for its Python scripting capability, and relies on PyDev for integrated debugging with Eclipse.  This used to work nicely in PyDev 6.3.1, but in later versions (I believe 7.3 and later), the breakpoint won't catch.  I've done quite a bit of debugging in Ghidra to determine that the problem has something to do with Ghidra running the python script from a daemon thread.  I've reduced the problem to this simple standalone Java example:

**Test.java** (requires jython library):
```
public class Test {
	public static void main(String[] args) throws Exception {
		ExecutorService ex = Executors.newSingleThreadExecutor(new ThreadFactory() {
			@Override
			public Thread newThread(Runnable r) {
				Thread t = Executors.defaultThreadFactory().newThread(r);
				t.setDaemon(true);
				return t;
			}
		});
		ex.execute(() -> {
			new InteractiveInterpreter().execfile("c:\\users\\ryan\\ghidra_scripts\\test.py");
		});

		while (true);
	}
}
```

**test.py**:
```
import sys;sys.path.append(r'C:\eclipse\dropins\PyDev 7.5.0\plugins\org.python.pydev.core_7.5.0.202001101138\pysrc')
import pydevd;pydevd.settrace()
 
print "test"
print "test"
print "test"
```

If you change `t.setDaemon(true)` to `false`, the breakpoint will catch.  I don't believe it will be feasible to change the behavior of Ghidra's complex threading system, so hopefully there is a known workaround, or a possible fix that can be put in.

Thanks!

**Comment by jpleasu** [comment]
To prevent the check thread from shutting down the debug client, daemon threads can be labeled as main threads.  In each user daemon thread, set the `__pydevd_main_thread` attribute, e.g.
```python
import pydevd
pydevd.threadingCurrentThread().__pydevd_main_thread = True
```
