### ISSUE TITLE
Source format and Organize Imports conflict with each other

### ISSUE THREAD

**Issue by dropslowly** [fabioz/PyDev.Debugger#180]
Run Source Format and there is one line between imports and code. Run Organize imports and it puts two lines between imports and code. They should not conflict.

**Comment by fabioz** [comment]
Humm... I guess this is the wrong repo to report this kind of issues (this repo is just for the pydev debugger).

Issues for PyDev itself are expected at: https://www.brainwy.com/tracker/PyDev/
