### ISSUE TITLE
invalid literal for int() with base 10 when trying to run project in remote server

### ISSUE THREAD

**Issue by OoiYueYing** [fabioz/PyDev.Debugger#182]
Traceback (most recent call last):
  File "/home/yueying/.local/lib/python3.6/site-packages/_pydevd_bundle/pydevd_comm.py", line 316, in _on_run
    cmd_id = int(args[0])
ValueError: invalid literal for int() with base 10: 'SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3\r'
Can't process net command: SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3

**Comment by OoiYueYing** [comment]
^ i was trying out [this tutorial](https://www.jetbrains.com/help/pycharm/remote-debugging-with-product.html#remote-debug-config ) and i ran into the above error. Not sure why?

**Comment by fabioz** [comment]
Well, PyCharm currently uses its own fork of pydevd (so, you should check with them as the lines in this report don't match the source code and even if I do some change here you wouldn't get it until they upgrade it there).

**Comment by zj56** [comment]
Note that the two IP addresses are different, one is the address of the remote server and the other is the address of the local server. If two addresses are set to the same, this error will occur.
