### ISSUE TITLE
unable to find translation / Trying to add breakpoint to file that does not exist:

### ISSUE THREAD

**Issue by WolfgangFahl** [fabioz/PyDev.Debugger#184]
I am trying to follow:

https://stackoverflow.com/questions/7999526/is-there-any-way-to-modify-the-pydevd-file-utils-paths-from-eclipse-to-python-va/41765551

and there are two upvoted answers. 

I tried configuring the mapping in the Eclipse dialog and via software. So far with no success.

At least i get an error message when i try:
```python
import os
os.environ.setdefault("PATHS_FROM_ECLIPSE_TO_PYTHON",'[["/Users/wf/Documents/py-workspace/piwodebug/Mail.py","/tmp/Mail.py"]]')
import pydevd
pydevd.settrace(...
```
This is in the context of https://www.mediawiki.org/wiki/Extension:Piwo#Debugging where the tmp directory might actually not be the tmp directory but a firejailed tmp file where i can't know the path in advance ...

The message below is strange for me:

pydev debugger: unable to find translation for: "/Users/wf/Documents/pyworkspace/piwodebug/Mail.py" in ["/Users/wf/Documents/py-workspace/piwodebug/Mail.py"] (please revise your path mappings).

pydev debugger: warning: Trying to add breakpoint to file that does not exist: /Users/wf/Documents/pyworkspace/piwodebug/Mail.py (will have no effect).

I'd appreciate a working example how to set the path mapping up.

**Comment by WolfgangFahl** [comment]
see also https://stackoverflow.com/a/51457761/1497139

**Comment by WolfgangFahl** [comment]
https://www.pydev.org/manual_adv_remote_debugger.html still documents to modify a source file ... is that really necessary?

**Comment by WolfgangFahl** [comment]
I found:
* https://www.pydev.org/manual_adv_remote_debugger.html
* https://stackoverflow.com/questions/39041733/pydev-debugger-warning-trying-to-add-breakpoint-to-file-that-does-not-exist
* https://stackoverflow.com/a/50295939/1497139
* https://github.com/fabioz/PyDev.Debugger/blob/master/pydevd_file_utils.py

and example in the source code

**Comment by WolfgangFahl** [comment]
After a few more hours of trial and error I get the effect that things work on one of my machines but not the other.
Working environment:
* Eclipse 2019-12 (4.14.0) Build id: 20191212-1212
* macOS High Sierra
* macPorts 2.6.3
```bash
python3 --version
Python 3.8.5
```

The code being debugged is
```python
import os
import sys
print ("before debug is on: %s" % os.path.abspath(__file__))

piwo=None
# check we are called from the Piwo extension
if 'MW_PIWO' in os.environ:
    # add path to mw.py
    piwo=os.environ['MW_PIWO']
    sys.path.append(piwo)
    # import it
    import mw
    # activate debugging
    debugServer=None
    debugServer="mars.bitplan.com"
    if debugServer is not None:
        import pydevd
        #os.environ["PATHS_FROM_ECLIPSE_TO_PYTHON"]='[["/Users/wf/Documents/pyworkspace/piwodebug/", "/tmp/"]]'
        pydevd.settrace(debugServer, port=5678,stdoutToServer=True, stderrToServer=True)

print ("after debug is on: %s" % os.path.abspath(__file__))

a = 1
b = 2
c = a + b
```

**Comment by WolfgangFahl** [comment]
The fun thing is - a minute later things don't work anymore. So this seems to be a left over of some successful setting of yesterday - unfortunately i don't know which of the fancy combinations would work. 
One of the problems seems to be a symbolic link from pyworkspace to py-workspace. The two machines are made compatible by this symlink but the pydevd seems to have trouble with such symlinks. I'll now remove the symlinks and use the same style on both machines and get back

**Comment by WolfgangFahl** [comment]
I am stuck again - the code won't work in both of my environments.
The second Eclipse machine is:

* macOS 10.13.6
* Eclipse 2020-09Build id: 20200910-1200

The server remotely to be debugged is:
* Ubuntu 20.04 LTS
```python
python3 --version
Python 3.8.5
```
```python
pip show pydevd
Name: pydevd
Version: 2.0.0
Summary: PyDev.Debugger (used in PyDev, PyCharm and VSCode Python)
Home-page: https://github.com/fabioz/PyDev.Debugger/
Author: Fabio Zadrozny and others
```

**Comment by WolfgangFahl** [comment]
a search for "Trying to add breakpoint to file that does not exist:" leads to:
* https://github.com/microsoft/vscode-python/issues/3567

**Comment by WolfgangFahl** [comment]
I am still having the issue despite some comment i got from a different ticket system.

**Comment by WolfgangFahl** [comment]
I added https://www.brainwy.com/tracker/PyDev/1123 as a feature request

**Comment by WolfgangFahl** [comment]
https://www.brainwy.com/tracker/PyDev/1119 does not fullfill basic remote debuggin needs.

When setting up remote debugging with e.g
       import pydevd
        pydevd.settrace(args.debugServer,  port=args.debugPort,stdoutToServer=True, stderrToServer=True)

the remote debugging will begin and when a break point is set warnings like: pydev debugger: warning: Trying to add breakpoint to file that does not exist: /Users/wf/Documents/pyworkspace/pyWikiCMS/frontend/webserver.py (will have no effect).
 will show since there is no proper path mapping negotation between the client and the server side going on. The warning does not state what to do so people will start searching for a solution e.g. find https://stackoverflow.com/questions/39041733/pydev-debugger-warning-trying-to-add-breakpoint-to-file-that-does-not-exist which does not really help. In fact i did not find any good explanation on any of the https://stackoverflow.com/questions/tagged/pydev how to get path mapping properly working from the remote side so i assume it is currently not possible that's why i am opening this ticket as a feature request. See e.g. https://stackoverflow.com/questions/51431742/configure-path-mappings-between-two-remote-system-to-make-breakpoints-work-in-py how people struggle for days to get things working since the basic need of remotely and simply handling the situation is not fullfilled.

See my own github ticket https://github.com/fabioz/PyDev.Debugger/issues/184 which is still open. 

https://www.pydev.org/manual_adv_remote_debugger.html

does IMHO not properly describe how to properly debug. It still has the comment:

Note: if the target machine does not have the same paths as the client machine, the file pydevd_file_utils.py must be edited to properly translate the paths from one machine to the other - see comments on that file.

Without really saying what to do. IMHO this is an akward procedure since in my use case i need to debug the same software on different machines with using always the same remote machine. I'd have to change a local python file dozen of times if things stay like they are and I'd have to think abouthe operating system differences all the time. I'd love to run things on e.g. ocker, linux, windows, macos and alway use my mac OS Eclipse IDE as the remote debugging environment 

Please note that a major reason for this feature request is that I am trying to debug an open source library i am creating so i might not be able to modify the code of the client at all. A workaround might be to be able to pass in some external configuration e.g. as a json mapping. The current Environment variable style is not easy to understand at this time since it's not even clear what the local and remote side of things is and the documentation with an example seems to be incomplete.

**Comment by WolfgangFahl** [comment]
This is currently my workaround:
```python
from pydevd_file_utils import setup_client_server_paths
    ...
    parser.add_argument('--debug',
                                 action='store_true',
                                 help="run in debug mode")
    parser.add_argument('--debugServer',
                                 help="remote debug Server")
    parser.add_argument('--debugPort',type=int,
                                 help="remote debug Port",default=5678)
    parser.add_argument('--debugPathMapping',nargs='+',help="remote debug Server path mapping - needs two arguments 1st: remotePath 2nd: local Path")
    args=parser.parse_args()
    if args.debugServer:
        import pydevd
        print (args.debugPathMapping,flush=True)
        if args.debugPathMapping:
            if len(args.debugPathMapping)==2:
                remotePath=args.debugPathMapping[0] # path on the remote debugger side
                localPath=args.debugPathMapping[1]  # path on the local machine where the code runs
                MY_PATHS_FROM_ECLIPSE_TO_PYTHON = [
                    (remotePath, localPath),
                ]
                setup_client_server_paths(MY_PATHS_FROM_ECLIPSE_TO_PYTHON)
                #os.environ["PATHS_FROM_ECLIPSE_TO_PYTHON"]='[["%s", "%s"]]' % (remotePath,localPath)
                #print("trying to debug with PATHS_FROM_ECLIPSE_TO_PYTHON=%s" % os.environ["PATHS_FROM_ECLIPSE_TO_PYTHON"]);
     
        pydevd.settrace(args.debugServer, port=args.debugPort,stdoutToServer=True, stderrToServer=True)
```

**Comment by fabioz** [comment]
Hi Wolfgang, great that you got it working

 I answered you in the https://www.brainwy.com/tracker/PyDev/1123 ticket and the work on https://www.brainwy.com/tracker/PyDev/1119 will also take care of improving the docs so that things are more discoverable.

Closing this one since work is being tracked in those tickets.

**Comment by WolfgangFahl** [comment]
The problem reappears with pydevd-2.10.0 - the workaround doesn't seem to work any more ...
