### ISSUE TITLE
any tutorial to show how to integrate this debugger in IDE project?

### ISSUE THREAD

**Issue by kingctan** [fabioz/PyDev.Debugger#194]
any tutorial to show how to integrate this debugger in IDE project?

**Comment by fabioz** [comment]
Unfortunately no... The best place to see how to setup things would be in the tests.

Most of what'd be in a client is in one of the following files:

https://github.com/fabioz/PyDev.Debugger/blob/main/tests_python/debugger_unittest.py
https://github.com/fabioz/PyDev.Debugger/blob/main/tests_python/debugger_fixtures.py

https://github.com/fabioz/PyDev.Debugger/blob/main/tests_python/test_debugger_json.py covers tests using the Debug Adapter Protocol

https://github.com/fabioz/PyDev.Debugger/blob/main/tests_python/test_debugger.py covers tests using the custom XML protocol.
