### ISSUE TITLE
2.4.x Missing file pydevd_frame_evaluator.template.pyx error during cython setup

### ISSUE THREAD

**Issue by rjones09** [fabioz/PyDev.Debugger#197]
I've used eclipse successfully with pydevd for several years without problems. I recently created a new python venv and I can no longer import pydevd without error. Eclipse gives me a warning:
"Warning: Debugger speedups using cython not found. Run '"C:\Users\randy\AppData\Local\Programs\finDev\Scripts\python.exe" "C:\Users\randy\AppData\Local\Programs\finDev\lib\site-packages\setup_cython.py" build_ext --inplace' to build."

When I try to run the command above I get a file not found error against _pydevd_frame_evaluator.template.pyx_ . The folder is there but not the specific file. I've pasted the shell output below.

`(finDev) C:\Users\randy\AppData\Local\Programs\finDev\Lib\site-packages>pip install pydevd
Collecting pydevd
  Downloading pydevd-2.4.1-cp39-cp39-win_amd64.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 652 kB/s
Installing collected packages: pydevd
Successfully installed pydevd-2.4.1

(finDev) C:\Users\randy\AppData\Local\Programs\finDev\Lib\site-packages>"C:\Users\randy\AppData\Local\Programs\finDev\Scripts\python.exe" "C:\Users\randy\AppData\Local\Programs\finDev\lib\site-packages\setup_cython.py" build_ext --inplace
running build_ext
building '_pydevd_bundle.pydevd_cython' extension
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPy_BUILD_CORE_MODULE=1 -IC:\Users\randy\AppData\Local\Programs\finDev\include -IC:\Users\randy\AppData\Local\Programs\Python\Python39\include -IC:\Users\randy\AppData\Local\Programs\Python\Python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /Tc_pydevd_bundle\pydevd_cython.c /Fobuild\temp.win-amd64-3.9\Release\_pydevd_bundle\pydevd_cython.obj
pydevd_cython.c
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\randy\AppData\Local\Programs\finDev\libs /LIBPATH:C:\Users\randy\AppData\Local\Programs\Python\Python39\libs /LIBPATH:C:\Users\randy\AppData\Local\Programs\Python\Python39 /LIBPATH:C:\Users\randy\AppData\Local\Programs\finDev\PCbuild\amd64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64 /EXPORT:PyInit_pydevd_cython build\temp.win-amd64-3.9\Release\_pydevd_bundle\pydevd_cython.obj /OUT:build\lib.win-amd64-3.9\_pydevd_bundle\pydevd_cython.cp39-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.9\Release\_pydevd_bundle\pydevd_cython.cp39-win_amd64.lib
   Creating library build\temp.win-amd64-3.9\Release\_pydevd_bundle\pydevd_cython.cp39-win_amd64.lib and object build\temp.win-amd64-3.9\Release\_pydevd_bundle\pydevd_cython.cp39-win_amd64.exp
Generating code
Finished generating code
copying build\lib.win-amd64-3.9\_pydevd_bundle\pydevd_cython.cp39-win_amd64.pyd -> _pydevd_bundle
Traceback (most recent call last):
  File "C:\Users\randy\AppData\Local\Programs\finDev\lib\site-packages\setup_cython.py", line 241, in <module>
    build_extension("_pydevd_frame_eval", extension_name, target_frame_eval, force_cython, extension_folder, True, template=True)
  File "C:\Users\randy\AppData\Local\Programs\finDev\lib\site-packages\setup_cython.py", line 91, in build_extension
    with open(pyx_template_file, 'r') as stream:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\randy\\AppData\\Local\\Programs\\finDev\\lib\\site-packages\\_pydevd_frame_eval\\pydevd_frame_evaluator.template.pyx'`

My environment is a python 3.9.x venv with the following site packages installed:
(finDev) C:\Users\randy\AppData\Local\Programs\finDev\Lib\site-packages>pip list
Package                 Version
----------------------- ----------
certifi                 2020.12.5
chardet                 4.0.0
cycler                  0.10.0
Cython                  0.29.22
docutils                0.17
greenlet                1.0.0
idna                    2.10
Kivy                    2.0.0
kivy-deps.angle         0.3.0
kivy-deps.glew          0.3.0
kivy-deps.sdl2          0.3.1
Kivy-Garden             0.1.4
kivy-garden.contextmenu 0.1.0.dev1
kivycalendar3           0.0.3
kiwisolver              1.3.1
matplotlib              3.4.1
numpy                   1.20.2
Pillow                  8.2.0
pip                     21.0.1
pydevd                  2.4.1
Pygments                2.8.1
pyparsing               2.4.7
pypiwin32               223
python-dateutil         2.8.1
pywin32                 300
requests                2.25.1
setuptools              54.1.2
six                     1.15.0
SQLAlchemy              1.4.7
urllib3                 1.26.4
wheel                   0.36.2

**Comment by fabioz** [comment]
Sorry about that... it seems something that's meant to be used only in dev mode made it to your env. I'll fix that for the next release...

In the meanwhile, the workaround for that is changing `setup_cython.py` locally to change `template=True` to `template=False` 

-- i.e.: change line `241` of `setup_cython.py` to:

`build_extension("_pydevd_frame_eval", extension_name, target_frame_eval, force_cython, extension_folder, True, template=False)`

**Comment by rjones09** [comment]
Thank you!

**Comment by rjones09** [comment]
Seems ok now.
