### ISSUE TITLE
import statement in pydev_imports.py always fails

### ISSUE THREAD

**Issue by juliangilbey** [fabioz/PyDev.Debugger#212]
These lines:
https://github.com/fabioz/PyDev.Debugger/blob/9312aa554d4b9dd38513cb232d9c3d94bf620095/_pydev_bundle/pydev_imports.py#L17-L18
first import the module `_pydev_SimpleXMLRPCServer` and then try to import a symbol from `_pydev_SimpleXMLRPCServer`.  Unfortunately this second module cannot be found, as it does not lie on the search path, even though `_pydev_SimpleXMLRPCServer` has been loaded.  Perhaps this works in Python 2.x, but it certainly doesn't in Python 3.x.  Presumably the code should instead read:
```python
            from _pydev_imps._pydev_saved_modules import _pydev_SimpleXMLRPCServer
            from _pydev_imps._pydev_SimpleXMLRPCServer import SimpleXMLRPCServer
```

**Comment by fabioz** [comment]
I'm in the process of dropping Python 2.7 completely from the codebase and this will definitely be changed during that process.

**Comment by juliangilbey** [comment]
Thanks @fabioz, and I'm pleased to see this simplified Python 3-only version! I'm currently attempting to package pydevd for Debian, so I'll be in contact as I find more issues.
