### ISSUE TITLE
How to compile pydevd_frame_evaluator.c in Python 3.11?

### ISSUE THREAD

**Issue by juliangilbey** [fabioz/PyDev.Debugger#238]
Debian has just added Python 3.11 to its unstable distribution as a supported version of Python. Unfortunately this breaks the pydevd and debugpy builds because of this unresolved TODO:

https://github.com/fabioz/PyDev.Debugger/blob/f7ab0d0749298906329842c254d981d1763d0bc9/_pydevd_frame_eval/pydevd_frame_evaluator.pxd#L56

Do you have any suggestions of how to address this so that these packages can continue to be compiled?

Thanks!

**Comment by juliangilbey** [comment]
I spoke too quickly; I had a look at the problem and figured out how to solve it. PR now submitted!

**Comment by juliangilbey** [comment]
Oh, I'm wrong. It's part of the solution, but far from complete. I'll write more on https://github.com/microsoft/debugpy/issues/939 as I realise that's where you're mainly working.

**Comment by fabioz** [comment]
The frame eval mode is not supposed to be compiled on Python 3.11 right now (see comment on: https://github.com/microsoft/debugpy/issues/939#issuecomment-1318420128)
