### ISSUE TITLE
Missing tag for 2.9.4

### ISSUE THREAD

**Issue by mgorny** [fabioz/PyDev.Debugger#244]
There doesn't seem to be a tag corresponding to the pypi 2.9.4 release.

**Comment by fabioz** [comment]
It's there now (but just to note, there'll be a 2.9.5 shortly because apparently the README is no longer there due to some setuptools backward incompatibility changes).

**Comment by mgorny** [comment]
Ok, thanks. We'll wait for 2.0.5 (hopefully with a tag ;-)) then.
