### ISSUE TITLE
Encryption/TLS support?

### ISSUE THREAD

**Issue by martijnthe** [fabioz/PyDev.Debugger#247]
Hello,

First off, thanks very much for creating this wonderful tool!

I have a question: is there any built-in support for encryption/TLS? Or are you expected to not use this over untrusted networks (the internet) / always use a SSH tunnel to the remote machine or something along those lines?

Thanks!
Martijn

**Comment by fabioz** [comment]
Hello Martin. You're always supposed to do the SSH tunneling yourself in these cases.
