### ISSUE TITLE
RecursionError with OpenAI Library in PyDev.Debugger of PyCharm 2023.3

### ISSUE THREAD

**Issue by xuing** [fabioz/PyDev.Debugger#266]
I encountered a RecursionError while debugging a Python script that imports the OpenAI library in PyCharm using the PyDev.Debugger.

For detailed information about the issue, please refer to following

openai/openai-python#906

[Jetbrains youtrack](https://youtrack.jetbrains.com/issue/PY-64445/RecursionError-with-OpenAI-Library-in-PyDev.Debugger-of-PyCharm-2023.3-RC)

**Comment by captain828** [comment]
Happens in the latest PyCharm stable as well. (2023.3)

**Comment by grzesadam** [comment]
It happens in 2023.3.1, persists in 2023.3.2 RC, but does nto happen in 2023.2.5

**Comment by khaledmsm** [comment]
any update ?

**Comment by dielect** [comment]
I have also completed this issue, my version is March 2, 2023, I am currently retiring the review version, and I hope it will be useful.

**Comment by captain828** [comment]
Seems to be fixed with the latest OpenAI library (1.10.0) and the latest Pycharm stable (2023.3.3),

**Comment by xuing** [comment]
> Seems to be fixed with the latest OpenAI library (1.10.0) and the latest Pycharm stable (2023.3.3),
Yes, although the contributor still recommends that the PyCharm team also fix this.
Feel free to close the issues.

https://github.com/openai/openai-python/issues/906#issuecomment-1894145644

**Comment by fabioz** [comment]
This issue is only in the PyCharm fork, so closing here as plain pydevd does not have this issue.
