### ISSUE TITLE
thread_id is expected to be string instead of int

### ISSUE THREAD

**Issue by Kitso1999** [fabioz/PyDev.Debugger#275]
Hi, I'm trying to embed python debugger in a QtWidgets application, using [cppdap](https://github.com/google/cppdap) and [debugpy](https://github.com/microsoft/debugpy). As you may know, debugpy uses this library as debug server.

I'm having trouble with DAP requests that use thread ids. The major ones are [continue](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Continue) and [pause](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Pause) requests: you can see that threadId field is defined to be an integer. Consequently, cppdap and debugpy both pass it to pydevd as an integer, but the functions in [pydevd_thread_lifecycle.py](https://github.com/fabioz/PyDev.Debugger/blob/main/_pydevd_bundle/pydevd_thread_lifecycle.py) expect it to be of type string. Therefore, pydevd crashes at [line 65](https://github.com/fabioz/PyDev.Debugger/blob/main/_pydevd_bundle/pydevd_thread_lifecycle.py#L65) or throws unnecessary exception at [line 17](https://github.com/fabioz/PyDev.Debugger/blob/main/_pydevd_bundle/pydevd_thread_lifecycle.py#L17) for other requests, such as [next](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Next), [step in](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_StepIn) and [step out](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_StepOut).

I explicitly casted thread ids as string for these functions and it works well. Would it be an acceptable solution to do the same here in the official repo? If not, what would you suggest?

**Comment by fabioz** [comment]
The internal thread id (which must be a string) is different from the DAP thread id (a number should be used when dealing with the DAP: https://github.com/fabioz/PyDev.Debugger/blob/main/_pydevd_bundle/_debug_adapter/pydevd_base_schema.py#L19).

So, not sure exactly what you're doing, but if you're dealing with the debug adapter protocol only `int` numbers should be exchanged.

**Comment by Kitso1999** [comment]
That is exactly how I do it. cppdap sends an integer as DAP thread id to debugpy. Then it seems that debugpy sends this id unchanged, but as you can see in my old fragment of pydevd logs, the thread id isn't handled properly:

```
.00s - processing internal command: InternalThreadCommands(None, (), {})
7.82s - Process ContinueRequest: {
    "arguments": {
        "singleThread": false,
        "threadId": 0
    },
    "command": "continue",
    "seq": 7,
    "type": "request"
}

0.00s - Resuming threads: 0 (except thread: None)
Traceback (most recent call last):
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python311\Lib\site-packages\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_comm.py", line 252, in _on_run
    self.process_net_command_json(self.py_db, json_contents)
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python311\Lib\site-packages\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_process_net_command_json.py", line 193, in process_net_command_json
    cmd = on_request(py_db, request)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python311\Lib\site-packages\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_process_net_command_json.py", line 549, in on_continue_request
    self.api.request_resume_thread(thread_id)
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python311\Lib\site-packages\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_api.py", line 197, in request_resume_thread
    resume_threads(thread_id)
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python311\Lib\site-packages\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_thread_lifecycle.py", line 61, in resume_threads
    elif thread_id.startswith('__frame__:'):
         ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'startswith'
0.12s - ReaderThread: exit
```

It seems to me that pydevd is responsible for conversion between DAP thread id and internal thread id, but I remember I logged this id once or twice and it was the same as the DAP thread id that I passed in.

**Comment by fabioz** [comment]
The problem is probably that you're passing `threadId==0`. You need to pass a valid thread id (the one where you were stopped). Using `0` is not a valid thread id.

**Comment by fabioz** [comment]
p.s.: please confirm whether you're actually passing a thread id which you've previously received...

**Comment by Kitso1999** [comment]
That is correct, I was passing invalid thread id. I fixed it and now it works!

Thanks for helping out!
