### ISSUE TITLE
[WinError 2] 系统找不到指定的文件。: 'you python path\python3.10.10\\python310.zip'

### ISSUE THREAD

**Issue by xiezhipeng-git** [fabioz/PyDev.Debugger#281]
发生异常: FileNotFoundError
[WinError 2] 系统找不到指定的文件。: 'd:\\my\\env\\python3.10.10\\python310.zip'
  File "D:\my\env\python3.10.10\Lib\genericpath.py", line 19, in exists
    os.stat(path)
  File "D:\my\env\python3.10.10\Lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\my\env\python3.10.10\Lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'd:\\my\\env\\python3.10.10\\python310.zip'

Suddenly unable to debug. This bug appears immediately after debugging. I don't know how to solve it either. Can I clear the cache and try to solve it? So where is the cache path?

**Comment by fabioz** [comment]
That's weird, pydevd doesn't have any reference to runpy (it does have a vendored version for running with `-m`, but that is not appearing in the traceback, so, it doesn't seem to be related to that).

So, given that neither PyDev in Eclipse nor the PyDev in VSCode (https://marketplace.visualstudio.com/search?term=pydev&target=VSCode&category=All%20categories&sortBy=Relevance) seem to be responsible for this error I'll have to close this issue...

If you're using a different extension in VSCode or another client, you should report there (if you can reproduce in the actual PyDev for VSCode or Eclipse then feel free to reopen the issue).

**Comment by xiezhipeng-git** [comment]
vscode Must appear
But changing the folder name does not solve this problem. If you change it back, it must be realized

**Comment by xiezhipeng-git** [comment]
I guess maybe because I make The project a same name zipfile.then the problem must appear
