### ISSUE TITLE
Some tests causing Python 3.12 to crash

### ISSUE THREAD

**Issue by juliangilbey** [fabioz/PyDev.Debugger#283]
I have been trying to run the test suite for Debian, but 3.1.0 now causes Python 3.12 to crash with a segmentation fault.  The tests which are causing the crash are (so far) in `tests_python/test_evaluate_expression.py`, so I ran `test_evaluate_expression_basic` manually, using a debug-enabled Python 3.12 (the regular Python 3.12 just crashes with an unspecified Segmentation fault):

```python
$ python3.12-dbg
Python 3.12.4 (main, Jun 12 2024, 19:06:53) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> SOME_LST = ["foo", "bar"]
>>> BAR = "bar"
>>> FOO = "foo"
>>> global_frame = sys._getframe()
>>> 
>>> def obtain_frame():
...     A = 1
...     B = 2
...     yield sys._getframe()
... 
>>> from _pydevd_bundle.pydevd_vars import evaluate_expression
>>> def check(frame):
...     evaluate_expression(None, frame, "some_var = 1", is_exec=True)
... 
>>> check(next(iter(obtain_frame())))
23.64s - _evaluate_with_timeouts called without py_db!
python3.12-dbg: ../Objects/frameobject.c:1205: frame_get_var: Assertion `value == NULL' failed.
Aborted
```
I have no idea what is causing this bug, or how serious it is.

**Comment by fabioz** [comment]
A crash here would be a CPython bug there, not much to do in pydevd.

It seems to be the same thing as: https://github.com/python/cpython/issues/125723, but I may be wrong (as that's a 3.13 bug, but maybe it creeped onto 3.12).
