### ISSUE TITLE
Support debugging 3.13

### ISSUE THREAD

**Issue by rchiodo** [fabioz/PyDev.Debugger#291]
There's been some changes in CPython, which seems to make Pydevd not able to debug:

https://github.com/python/cpython/commit/33da0e844c922b3dcded75fbb9b7be67cb013a17#diff-b250d3d0e0d909784a67083e9069ce507513a67e8514a011e2f364027e25e0b0

I didn't go much farther than that, so there might be other internals that would have to change.

**Comment by rchiodo** [comment]
@fabioz is this something you're actively working on? I didn't see any other issues on it.  We'd like to ship debugpy with this working [ASAP](https://github.com/microsoft/debugpy/issues/1689), so if you're not busy getting this to work, I can push that change back here when I'm done.

**Comment by fabioz** [comment]
Yeah, new versions always need work as the debugger needs to work around a bunch of internal things in CPython... I'm not sure when I'll be able to tackle this, so, if you'd like to give it a go that'd be nice (it'd be nice to have that other PR: https://github.com/fabioz/PyDev.Debugger/pull/290 in first though).

As a note, I'd suggest you start from the `pydevd` code and then port to `debugpy`.

Reasons:
1. It's easier to not have the additional `debugpy` layer when debugging (so when you run pytest it's just the test and the debugger, whereas in debugpy you always have an additional layer of indirection which makes it a bit more cumbersome to debug core things).
2. The test suite tests more internal things which is handy for new python versions (possibly as you've seen `debugpy` does have scenarios not matching here, but the usual is the other way around).

**Comment by rchiodo** [comment]
> (it'd be nice to have that other PR: https://github.com/fabioz/PyDev.Debugger/pull/290 in first though)

I'd love to finish this but we're facing pressure to get something working ASAP. I'm about halfway done with your comments but we'll likely have to fix debugpy before I can go back to working on that PR :(

**Comment by rchiodo** [comment]
3.13 changes weren't very involved. I'm back to working on the other PR. Once that goes through I'll send another update for 3.13 :)
