### ISSUE TITLE
pydef_import_hook ... is not a valid Win32 application

### ISSUE THREAD

**Issue by L1n4** [fabioz/PyDev.Debugger#32]
Hi,
Im doing a project using PyCharm (4.0.6) and Python 3.4.3 including the exiv2 package.
Trying to import libexiv2python an error is traced back to the pydef_import_hook.py saying: 
module = self._system_import(name, *args, **kwargs)
ImportError: DLL load failed: %1 is not a valid Win32 application.

any idea what to to against it/ what I have done wrong?

furthermore import builtins is underlined rad saying that: Phyton version 2.7 does not have module builtins.
But I'm not even using the 2.7 version.

Please help me!
Thanks

**Comment by fabioz** [comment]
Well, that error usually means there's some mixup in the libraries (so, maybe somehow pyhon 3 and python 2 are mixed in your install?)

You can check that by running:

import sys
print('\n'.join(sorted(sys.path)))

before that import to see if there's anything wrong in the PYTHONPATH.

If everything is correct, also print the PATH environment variable:

print('\n'.join(os.environ['PATH'].split(os.pathsep)))

and check if there may be something wrong there.

Also, please add details on the os you're using.
