### ISSUE TITLE
recent deployment into eclipse fails

### ISSUE THREAD

**Issue by romanchyla** [fabioz/PyDev.Debugger#42]
Hello,
I can't report into pydev repository, so I'm at least trying here

i'm installing pydev into eclipse using command line (which I'm sure worked just last week)

```
./eclipse -nosplash -application org.eclipse.equinox.p2.director -repository  "$repository" -${action} "201510052309.PyDev"
```

today it fails with:

```
Installing 201510052309.PyDev 1.0.0.7877-cLFtnh7735C533C793K.
Installation failed.
An error occurred while collecting items to be installed
 session context was:(profile=_dvt_eclipse-mars_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
 Artifact not found: https://dl.bintray.com/fabioz/pydev/latest/plugins/com.python.pydev_4.4.0.201510052309.jar.
Caused by:  java.io.FileNotFoundException: https://dl.bintray.com/fabioz/pydev/latest/plugins/com.python.pydev_4.4.0.201510052309.jar
 Artifact not found: https://dl.bintray.com/fabioz/pydev/latest/plugins/com.python.pydev.analysis_4.4.0.201510052309.jar.
....
```

and the artifacts are indeed missing from the download site

i see a commit in pydev 2hours ago, is it just a matter of time (synchronization)?

**Comment by fabioz** [comment]
Short answer: Please use the official url given by http://www.pydev.org/download.html (i.e.: http://www.pydev.org/updates) -- it'll point you to the proper url.

Long answer: bintray doesn't allow editing releases after an elapsed amount of time (6 months I guess), so, there's no way to actually implement a 'latest' properly using it (and thus the latest release on bintray was removed).

Anyways, http://www.pydev.org/updates, which is the official url for the latest version is now changed to point to the latest version at each release (which right now is https://dl.bintray.com/fabioz/pydev/4.5.1), so, using the official update site url should fix the issue for you.

p.s.: please don't report PyDev issues in this repository. The official place to report issues for PyDev is https://sw-brainwy.rhcloud.com/tracker/PyDev/.
