### ISSUE TITLE
Link in build.cmd is broken

### ISSUE THREAD

**Issue by traff** [fabioz/PyDev.Debugger#43]
The link https://github.com/cython/cython/wiki/64BitCythonExtensionsOnWindows mentioned in build.cmd is broken. 

It is offered to create a new page.

**Comment by traff** [comment]
Probably this one is meant: https://github.com/cython/cython/wiki/CythonExtensionsOnWindows ?

**Comment by fabioz** [comment]
Yes, that's the one ;)
