### ISSUE TITLE
Syntax error in python3

### ISSUE THREAD

**Issue by Lagovas** [fabioz/PyDev.Debugger#49]
https://github.com/fabioz/PyDev.Debugger/blob/development/_pydev_imps/_pydev_xmlrpclib.py#L294
True and False is reserved words that can't be variables. So at this line have error: "SyntaxError: can't assign to keyword"

**Comment by fabioz** [comment]
Well, that should be a version only kept for old versions of Python (so, it shouldn't be imported by the debugger anyways when on Python 3, which means that the syntax should be Ok).

If it's being imported when on Python 3, please give the full stack trace (note, closing as it doesn't seem like a bug as it is -- feel free to comment if you have more details).

**Comment by Lagovas** [comment]
sorry, it was my fault
