### ISSUE TITLE
Object attributes changes in Debug > Variables window are lost

### ISSUE THREAD

**Issue by sgapn** [fabioz/PyDev.Debugger#56]
Test code: 

```
import pydevd

class Bunch:
    def __init__(self, **kwds):
        self.__dict__.update(kwds)

def test():
    a = 0
    resp = Bunch()
    resp.status_code  = 200
    pydevd.settrace("172.21.20.133", stdoutToServer=True, stderrToServer=True)
    print("Hello, world!")
    print(a, resp.status_code)

test()
```

If I try to change variable a to 100 in Debug > Variables window, it works. If I change resp.status_code  to 500 the updated value is displayed in the window but not in the running application. If I print locals() I get:

```
{'resp.status_code': 500, 'resp': <__main__.Bunch object at 0x0000000000D048D0>, 'a': 0}
```

"resp.status_code" is obviously not a valid variable name. Instead of changing resp attribute a wrong entry in locals() was created.

Environment: 
remote: python 3.5, pydevd 0.0.6
local: Eclipse 4.6, PyDev  5.1.2.201606231256

**Comment by fabioz** [comment]
Thanks for the report. Just fixed it:

https://github.com/fabioz/PyDev.Debugger/commit/4b40aae57ba05a383aad83deeda73993ad59e79c

(will be available for PyDev 5.2, but you can get that patch and apply locally).
