### ISSUE TITLE
Error when injecting code in target process. Error code: 3 (on windows)

### ISSUE THREAD

**Issue by sharpensteel** [fabioz/PyDev.Debugger#58]
I trying to attach to python3.5 process
`...... pydevd_attach_to_process\attach_pydevd.py" --port 53687 --pid 4140`

Having error:

> Connecting to 64 bits target
> Injecting dll
> Dll injected
> Allocating code in target process
> Writing code in target process
> Allocating return value memory in target process
> Injecting code to target process
> Waiting for code to complete
> Error when injecting code in target process. Error code: 3 (on windows)

Running `attach_pydevd.py` with administrator rights not helped

Yet i can successfuly attach to python2.7 process (64-bit also).

os: windows 7

**Comment by sharpensteel** [comment]
Tryed to run test suite:
`python add_code_to_python_process.py --test`
having same error:
> Error when injecting code in target process. Error code: 3 (on windows)

environment python3.5, windows7 x64

**Comment by fabioz** [comment]
The reason this happens is because Python 3.5 is currently not supported (when that feature was introduced it didn't exist and the code still hasn't been upgraded to support it).

**Comment by sharpensteel** [comment]
ok, attaching worked on python 3.4.4

**Comment by ZmeiGorynych** [comment]
Getting the same issue. Is there any plan for fixing this? No sane person is using 3.4 anymore when current is 3.6 (in particular I need asyncio features that only appeared in 3.5), making this potentially awesome feature totally useless :(

**Comment by fabioz** [comment]
Humm, this should actually be fixed in the latest release. Just forgot to close the issue.

Commit: https://github.com/fabioz/PyDev.Debugger/commit/b56559f690edd234f1c7253490a75f327600f046

**Comment by fabioz** [comment]
Are you using the latest PyDev?

**Comment by ZmeiGorynych** [comment]
Am using it through PyCharm, just found out the PyCharm version which apparently has the fix is pre-release https://youtrack.jetbrains.com/issue/PY-17986.

Now dowonloading the EAP to test...

**Comment by Almenon** [comment]
I just got the same error with latest pycharm (2018.2 community) windows 10 python 3.7

**Comment by fabioz** [comment]
This is a known issue (the attach to process needs to be updated to work with Python 3.7).

**Comment by hapylestat** [comment]
does the code still not updated for 3.7?

**Comment by fabioz** [comment]
Yes... Hopefully I'll be able to fix that before the end of this year.

**Comment by MaximilianHoffmann** [comment]
I have python 3.6.6 and it does not seem to work either.

**Comment by hwasiti** [comment]
@fabioz Would you mind re-open this issue? 
So we know when you will fix it. I tried it on python 3.7.0 and seems still does not work.

**Comment by hwasiti** [comment]
@MaximilianHoffmann
I tried it on windows with python 3.6.6 and it worked. 

A friend also tried it on Ubuntu 16.0.4 / python 3.6.7 and it worked.

**Comment by Vafa-Andalibi** [comment]
Having the same issue with Python 3.7.3 and pycharm 2019.1

**Comment by fabioz** [comment]
The next release will support Python 3.7 (most of it is already implemented).

**Comment by icodk** [comment]
Same issue with Python 3.7.3 and pycharm 2019.1.3 (community edition)
`Error when injecting code in target process. Error code: 3 (on windows)`

**Comment by tngreene** [comment]
Hi, any update on this? I'm trying to profile Blender 2.80. I attach to the running processes, it says

`Error when injecting code in target process. Error code: 3 (on windows)`

I select the python.exe that Blender comes with, and it still says it. Blender 2.80 uses Python 3.7.0.

Any idea when a version that will work with Python 3.7.0? I'm really hoping to debug some performance issues and this was my tool of choice. Nothing else works as good as this for Blender.

**Comment by fabioz** [comment]
This is fixed in pydevd. PyCharm needs to update their fork.

**Comment by tngreene** [comment]
I'm using PyVmMonitor, not PyCharm

**Comment by tngreene** [comment]
Sorry, I realize that I probably should have submitted this bug somewhere else. I was just so excited to find other people with the same error code as me.

**Comment by fabioz** [comment]
I do have to update pyvmmonitor ;)

**Comment by tngreene** [comment]
Any idea when that'll be so I can prioritize what bugs to work on?
