### ISSUE TITLE
feature request: port qt5 backend for IPython console

### ISSUE THREAD

**Issue by mickeydonkey** [fabioz/PyDev.Debugger#59]
In IPython console `%matplotlib qt5` raises this error:  
`IPython.core.error.UsageError: Invalid GUI request 'qt5', valid ones are:dict_keys(['gtk', 'wx', 'pyglet', 'osx', 'tk', 'qt', 'qt4', 'none', 'gtk3', 'glut'])`

**Comment by fabioz** [comment]
Just fixed (will be available in the next PyDev release: 5.3.0).
