### ISSUE TITLE
python 2.6 support?

### ISSUE THREAD

**Issue by da1z** [fabioz/PyDev.Debugger#66]
is there plan to add python 2.6 ?
thanks

**Comment by fabioz** [comment]
It should actually support Python 2.6... if it's not, please provide the actual error you're having.

**Comment by da1z** [comment]
I mean compiling windows binaries for python 2.6

**Comment by fabioz** [comment]
Well, I believe you should be able to compile it locally (as pydevd uses cython for that and cython claims support for python 2.6). If you mean adding it to pypi, there are no plans for supporting pre-built versions of the speed up modules for python 2.6.

**Comment by da1z** [comment]
is there any instructions how to do that?
