### ISSUE TITLE
error: command 'cl.exe' failed: No such file or directory

### ISSUE THREAD

**Issue by da1z** [fabioz/PyDev.Debugger#67]
I am getting this error. Windows SDK 7.1 is present as a VS 2010. What am i doing worng?
thanks

**Comment by fabioz** [comment]
Which Python version are you using?

**Comment by da1z** [comment]
2.7

**Comment by da1z** [comment]
Ok, i was able to figure out the reason. Now i am getting 'cl.exe' failed with exit status -1073741515 for x32 version only

**Comment by da1z** [comment]
it was issue with my VS, sorry for bothering, i've fixed it
