### ISSUE TITLE
PyDBFrame instance has no attribute '_args'

### ISSUE THREAD

**Issue by ftreton-gpfw** [fabioz/PyDev.Debugger#70]
We are using Python 2.7.5 with Windows 10 and pydev_5.4.0.201611281236 with a quite complicated code (I cannot easily isolate it) and we are always having the same issue the python debug stop and the interpreter crash depending where you put a breakpoints in it (the location matter). 

So if we identify a location where putting a breakpoints in this particular position of code creating this error (always the same) :

`File "_pydevd_bundle\pydevd_cython_win32_27_64.pyx", line 509, in _pydevd_bundle.pydevd_cython_win32_27_64.PyDBFrame.trace_dispatch (_pydevd_bundle/pydevd_cython_win32_27_64.c:9786)
AttributeError: PyDBFrame instance has no attribute '_args'`

I have investigated this and it seems that in this configuration the Object in cython PyDBFrame passed to trace_dispatch is not correct, my guess is because he has been maybe destroy of pass with into garbage collector collected before the execution of trace_dispatch. 
The result is this case is a call of trace_dispatch  with an object PyDBFrame like it was just created without the call to __init__.

I managed to **solve this** (at least there is no crash anymore) without knowing exactly what happen because it was blocking for us. So I tried to instrument the code from _pydevd_bundle\pydevd_cython.pyx to debug it and add GC debug code. I tried until the code with 2 different break point uses cases does not crash anymore.
The solution was to not use the function NORM_PATHS_AND_BASE_CONTAINER from [_pydevd_bundle\pydevd_cython.pyx line 986](https://github.com/fabioz/PyDev.Debugger/blob/master/_pydevd_bundle/pydevd_cython.pyx#L986) :

So I replace the following line :
`abs_path_real_path_and_base = NORM_PATHS_AND_BASE_CONTAINER[frame.f_code.co_filename]`

And use instead the on in the fallback:

`abs_path_real_path_and_base = get_abs_path_real_path_and_base_from_frame(frame)`

This seems to have solve my crash but need to be fixed. Right now I am using this fix and get ready to disable cython if any other crash happen (in pure python debug version this working perfectly).

**Comment by fabioz** [comment]
I hope that the referenced commit does fix this issue. Will give a heads up when I publish a new nightly for PyDev.

**Comment by fabioz** [comment]
A new release was pushed which should solve that (PyDev 5.6.0), so, closing this issue.
