### ISSUE TITLE
Pydevd causes Windows Explorer to crash when used with PySide.

### ISSUE THREAD

**Issue by alexwidener** [fabioz/PyDev.Debugger#78]
I'll try to give as much feedback as I can, it's been a persistent issue for months and is easily reproducible. 

Using PySide 1.2.4, Pydev (inside of PyCharm 2017.1, and all 2016 versions) and Windows 7 build 7601.

Basically, when using PyCharm and launching an application that I've written in PySide inside of debug mode, it will launch the application and block Windows processes. Anything on the task bar, anything from launching, everything except for PyCharm.  Which I'm fine with, most of the time. 

But the issue is that exiting debugging, whether exiting cleanly via hitting my X button in the application window (which is handling a clean shut down of processes that it's performing), or by hitting the X button inside of PyCharm to shut down the debug process - both of these actions will cause Windows Explorer to lock up and need to be forced to end.  

You can click around on the task bar over and over and the "application not responding, would you like to close the process?" window will open repeatedly, until it finally lets go - this can take upwards of 60 seconds each time. And I launch into debug mode many times a day - it's getting to be an extreme loss of productivity.

If there are logs I can send, please let me know, I'll be happy to grab them. 

Debugging something not using PySide works perfectly fine, has no hiccups at all.

Thanks for looking at this.

**Comment by alexwidener** [comment]
Oh, I'd like to add: Absolutely 0 issues like this with Mac OS and various Linux distributions, I use them all frequently with PySide.

**Comment by fabioz** [comment]
Which Python version are you using? Can you provide a sample code with step-by-step instructions on how to reproduce this (including creating the environment and libraries you install)?

**Comment by alexwidener** [comment]
Python 2.7.13 (occurred on 2.7.12 as well)

I can explain the environment, it's rather complicated to setup, it's not easy like a virtualenv. 

We use this thing called [Rez](https://github.com/nerdvegas/rez) to host different versions of packages and have a central repository that everybody in the facility pulls from, rather than distributed versions. 

Therefore, our Python interpreter, the PySide package, and any other packages aren't hosted locally on the machine. 

Instructions to reproduce: 

1. Have PySide code in the project (I'm using a QDialog if that's of any help)
2. Press the debug button (doesn't matter if you have a breakpoint or not)
3. Once it launches, give it a second, then close with the X button in the Dialog or the X button in PyCharm.
4. Attempt to click around on the Windows Task Bar, try to open another application. It will lock up and I get a window that asks me if I want to close the process.

**Comment by fabioz** [comment]
Do you think you could reproduce it with steps in conda or virtualenv and provide the code to reproduce it (I mean, I'll try to reproduce it with what I've here, but I've done programming with PySide on my Windows machine and didn't notice anything strange as you're saying, so, I don't really have much hope on reproducing unless you have very detailed steps on how to reproduce your environment here)... also, unfortunately, I don't think I'll be able to setup Rez to reproduce that env here, so, it'd be nice to have steps to reproduce without it.

**Comment by alexwidener** [comment]
I'll see what I can get going - it will probably be next week, it's end of day here. 

Thanks for the really quick responses, I'll try and respond first thing Monday.

**Comment by alexwidener** [comment]
Hi, it looks like the issue isn't tied to Pydevd at all, it's been happening the last two days with the combination of Windows/PyCharm/PySide1 whether running in debug mode or just running standard. 

I'll go ahead and close the issue. 
Sorry to waste your time and thanks for the really quick responses.
