### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by alexmv** [fabioz/PyDev.Debugger#96]
Heya,

We're interested in using the new `PATHS_FROM_ECLISPE_TO_PYTHON` functionality (for an arbitrary path mapping which isn't Eclipse-related at all), but would ideally like to install from pip, rather than just `master`.  Are there plans for a release to PyPi in the short term?

Thanks for the excellent tool!

**Comment by alexmv** [comment]
Ping on this?

**Comment by wittekm** [comment]
Fabio appears to be out on vacation until this or next week :)
https://github.com/fabioz/PyDev.Debugger/pull/82#issuecomment-314735039

**Comment by alexmv** [comment]
Aha!  Thanks for the pointer.  Sorry for my impatience, Fabio -- enjoy your vacation!

**Comment by achuchev** [comment]
Any progress on this?

**Comment by fabioz** [comment]
Humm, sorry about this... I created a new `PyDev` release and I **should** have done a new `PyDev.Debugger` release too... will try to do it this week (probably on Thursday).

**Comment by wittekm** [comment]
Hey! Looks like 1.1.1 is now out on pypi - this can probably be closed out.
